name: Viro Bridge CI Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  bridge_build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: "https://registry.npmjs.org"

      # Setup dependencies for React Native
      # Note, brew and node are already installed on github workflows.
      - name: Setup Watchman
        run: brew install watchman
      - name: Install dependencies
        run: yarn
      - name: Install Pods
        working-directory: ./ios
        run: pod install

      - name: xcodebuild ViroReact IOS framework
        working-directory: ./ios
        run: |
          xcodebuild \
            -workspace ViroReact.xcworkspace/ \
            -scheme ViroReact \
            -sdk iphoneos \
            -configuration Release \
            clean build

      # Prepare Release scripts should also run our gradle builds
      # required for Android RN Frameworks.
      - name: Prepare Android Release
        run: ./prepare_release.sh

      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
